---
version: 2
jobs:
  build:

    machine:
      enabled: true

    working_directory: ~/openntpd

    steps:
      - setup_remote_docker:
          docker_layer_caching: true

      - checkout:
          path: ~/openntpd

      - run:
          name: "Install tools"
          command: "apt-get install -yq python python-dev python-pip"

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      - run:
          name: "Install virtualenv"
          command: |
            pip install virtualenv
            virtualenv ~/.venv
            source ~/.venv/bin/activate
            pip install -r requirements.txt


      - save_cache:
          paths:
            - ~/.venv
            - ~/.cache/pip
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: "run tests"
          command: |
            source ~/.venv/bin/activate
            molecule test
